title: Jackson Young
logo: assets/img/logo.JPG
description: I combine 5 years of academic physics (particle and space plasma) with 7 years of Data Science. Ranging from conducting and publishing geophysics research to budgeting multimillion-dollar monthly marketing budgets and advising executives in intraday business decisions. My toolset is used to produce results in a timely and efficient manner. I have acquired invaluable experience spending the last 12 years contributing to high-impact missions and I look forward to helping you complete yours!
show_downloads: false
theme: jekyll-theme-minimal
